'use client';

import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import type { Asset, AssetCategory, AssetStatus, AssetClassification } from '@/lib/definitions';
import { format } from 'date-fns';

const assetCategories: AssetCategory[] = ['Perangkat Keras', 'Aplikasi & Data', 'SDM & Pihak Ketiga', 'Sarana Pendukung'];
const assetStatuses: AssetStatus[] = ['Aktif', 'Dalam Perbaikan', 'Non-Aktif', 'Akan Kadaluarsa'];
const assetClassifications: AssetClassification[] = ['Tinggi', 'Sedang', 'Rendah', 'Belum Dinilai'];

const formSchema = z.object({
  name: z.string().min(3, 'Nama aset minimal 3 karakter.'),
  category: z.enum(assetCategories, { required_error: 'Kategori harus dipilih.' }),
  specifications: z.string().min(10, 'Spesifikasi minimal 10 karakter.'),
  location: z.string().min(3, 'Lokasi minimal 3 karakter.'),
  owner: z.string().min(3, 'Pemilik minimal 3 karakter.'),
  status: z.enum(assetStatuses, { required_error: 'Status harus dipilih.' }),
  purchaseDate: z.string().refine((val) => !isNaN(Date.parse(val)), { message: 'Tanggal pembelian tidak valid.' }),
  expiryDate: z.string().refine((val) => !isNaN(Date.parse(val)), { message: 'Tanggal kadaluarsa tidak valid.' }),
  classification: z.enum(assetClassifications, { required_error: 'Klasifikasi harus dipilih.' }),
});

type AssetFormValues = z.infer<typeof formSchema>;

interface AssetFormProps {
  asset: Asset | null;
  onSave: (asset: Asset) => void;
  onCancel: () => void;
}

export function AssetForm({ asset, onSave, onCancel }: AssetFormProps) {
  const defaultValues = asset ? {
    ...asset,
    purchaseDate: format(new Date(asset.purchaseDate), 'yyyy-MM-dd'),
    expiryDate: format(new Date(asset.expiryDate), 'yyyy-MM-dd'),
  } : {
    name: '',
    category: 'Perangkat Keras' as AssetCategory,
    specifications: '',
    location: '',
    owner: '',
    status: 'Aktif' as AssetStatus,
    purchaseDate: format(new Date(), 'yyyy-MM-dd'),
    expiryDate: format(new Date(new Date().setFullYear(new Date().getFullYear() + 5)), 'yyyy-MM-dd'),
    classification: 'Belum Dinilai' as AssetClassification,
  };
  
  const form = useForm<AssetFormValues>({
    resolver: zodResolver(formSchema),
    defaultValues,
  });

  function onSubmit(data: AssetFormValues) {
    onSave({
        ...data,
        id: asset?.id || '', // ID will be generated by parent if new
        assetCode: asset?.assetCode || '', // Asset code will be generated by parent if new
    });
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <FormField
            control={form.control}
            name="name"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Nama Aset</FormLabel>
                <FormControl>
                  <Input placeholder="cth. Server Database Utama" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={form.control}
            name="category"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Kategori</FormLabel>
                <Select onValueChange={field.onChange} defaultValue={field.value}>
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Pilih kategori aset" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    {assetCategories.map(cat => <SelectItem key={cat} value={cat}>{cat}</SelectItem>)}
                  </SelectContent>
                </Select>
                <FormMessage />
              </FormItem>
            )}
          />
        </div>

        <FormField
          control={form.control}
          name="specifications"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Spesifikasi</FormLabel>
              <FormControl>
                <Textarea placeholder="cth. Dell PowerEdge R740, 256GB RAM..." {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <FormField
                control={form.control}
                name="location"
                render={({ field }) => (
                <FormItem>
                    <FormLabel>Lokasi</FormLabel>
                    <FormControl>
                    <Input placeholder="cth. Ruang Server Lt. 1" {...field} />
                    </FormControl>
                    <FormMessage />
                </FormItem>
                )}
            />
            <FormField
                control={form.control}
                name="owner"
                render={({ field }) => (
                <FormItem>
                    <FormLabel>Pemilik</FormLabel>
                    <FormControl>
                    <Input placeholder="cth. Divisi TI" {...field} />
                    </FormControl>
                    <FormMessage />
                </FormItem>
                )}
            />
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <FormField
                control={form.control}
                name="status"
                render={({ field }) => (
                <FormItem>
                    <FormLabel>Status</FormLabel>
                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                        <SelectTrigger>
                        <SelectValue placeholder="Pilih status aset" />
                        </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                        {assetStatuses.map(stat => <SelectItem key={stat} value={stat}>{stat}</SelectItem>)}
                    </SelectContent>
                    </Select>
                    <FormMessage />
                </FormItem>
                )}
            />
            <FormField
                control={form.control}
                name="classification"
                render={({ field }) => (
                <FormItem>
                    <FormLabel>Klasifikasi Awal</FormLabel>
                     <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                        <SelectTrigger>
                        <SelectValue placeholder="Pilih klasifikasi" />
                        </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                        {assetClassifications.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}
                    </SelectContent>
                    </Select>
                    <FormMessage />
                </FormItem>
                )}
            />
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
             <FormField
                control={form.control}
                name="purchaseDate"
                render={({ field }) => (
                <FormItem>
                    <FormLabel>Tanggal Pembelian</FormLabel>
                    <FormControl>
                    <Input type="date" {...field} />
                    </FormControl>
                    <FormMessage />
                </FormItem>
                )}
            />
             <FormField
                control={form.control}
                name="expiryDate"
                render={({ field }) => (
                <FormItem>
                    <FormLabel>Tanggal Kadaluarsa</FormLabel>
                    <FormControl>
                    <Input type="date" {...field} />
                    </FormControl>
                    <FormMessage />
                </FormItem>
                )}
            />
        </div>


        <div className="flex justify-end gap-2 pt-4">
            <Button type="button" variant="outline" onClick={onCancel}>
                Batal
            </Button>
            <Button type="submit">Simpan</Button>
        </div>
      </form>
    </Form>
  );
}
