'use client';

import { zodResolver } from '@hookform/resolvers/zod';
import { useForm, useWatch } from 'react-hook-form';
import { z } from 'zod';
import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import type { Asset, AssetCategory, AssetStatus, AssetClassification } from '@/lib/definitions';
import { format } from 'date-fns';
import { Separator } from '../ui/separator';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { useEffect } from 'react';

const assetCategories: AssetCategory[] = ['Perangkat Keras', 'Perangkat Lunak', 'Sarana Pendukung', 'Data & Informasi', 'SDM & Pihak Ketiga'];
const assetStatuses: AssetStatus[] = ['Aktif', 'Dalam Perbaikan', 'Non-Aktif', 'Akan Kadaluarsa'];

const criteria = [
  { id: 'confidentiality', label: 'Kerahasiaan (Confidentiality)' },
  { id: 'integrity', label: 'Integritas (Integrity)' },
  { id: 'availability', label: 'Ketersediaan (Availability)' },
  { id: 'authenticity', label: 'Keaslian (Authenticity)' },
  { id: 'nonRepudiation', label: 'Non-repudiation' },
];

const scoreOptions = [
  { value: 1, label: '1 - Rendah' },
  { value: 2, label: '2 - Sedang' },
  { value: 3, label: '3 - Tinggi' },
];

const thresholds = {
  high: 11,
  medium: 6,
  low: 5,
};

const formSchema = z.object({
  name: z.string().min(3, 'Nama aset minimal 3 karakter.'),
  category: z.enum(assetCategories, { required_error: 'Kategori harus dipilih.' }),
  specifications: z.string().min(10, 'Spesifikasi minimal 10 karakter.'),
  location: z.string().min(3, 'Lokasi minimal 3 karakter.'),
  owner: z.string().min(3, 'Pemilik minimal 3 karakter.'),
  status: z.enum(assetStatuses, { required_error: 'Status harus dipilih.' }),
  purchaseDate: z.string().refine((val) => !isNaN(Date.parse(val)), { message: 'Tanggal pembelian tidak valid.' }),
  expiryDate: z.string().refine((val) => !isNaN(Date.parse(val)), { message: 'Tanggal kadaluarsa tidak valid.' }),
  confidentiality: z.coerce.number().min(1).max(3),
  integrity: z.coerce.number().min(1).max(3),
  availability: z.coerce.number().min(1).max(3),
  authenticity: z.coerce.number().min(1).max(3),
  nonRepudiation: z.coerce.number().min(1).max(3),
  classification: z.custom<AssetClassification>(),
});

type AssetFormValues = z.infer<typeof formSchema>;

interface AssetFormProps {
  asset: Asset | null;
  onSave: (asset: Asset) => void;
  onCancel: () => void;
}

const getClassification = (score: number): AssetClassification => {
    if (score >= thresholds.high) return 'Tinggi';
    if (score >= thresholds.medium) return 'Sedang';
    return 'Rendah';
};

export function AssetForm({ asset, onSave, onCancel }: AssetFormProps) {
  const defaultValues = asset ? {
    ...asset,
    purchaseDate: format(new Date(asset.purchaseDate), 'yyyy-MM-dd'),
    expiryDate: format(new Date(asset.expiryDate), 'yyyy-MM-dd'),
    confidentiality: 1, // Default scores for editing, can be adjusted
    integrity: 1,
    availability: 1,
    authenticity: 1,
    nonRepudiation: 1,
  } : {
    name: '',
    category: 'Perangkat Keras' as AssetCategory,
    specifications: '',
    location: '',
    owner: '',
    status: 'Aktif' as AssetStatus,
    purchaseDate: format(new Date(), 'yyyy-MM-dd'),
    expiryDate: format(new Date(new Date().setFullYear(new Date().getFullYear() + 3)), 'yyyy-MM-dd'),
    confidentiality: 1,
    integrity: 1,
    availability: 1,
    authenticity: 1,
    nonRepudiation: 1,
    classification: 'Rendah' as AssetClassification,
  };
  
  const form = useForm<AssetFormValues>({
    resolver: zodResolver(formSchema),
    defaultValues,
  });

  const watchedScores = useWatch({
    control: form.control,
    name: ["confidentiality", "integrity", "availability", "authenticity", "nonRepudiation"],
  });

  const totalScore = watchedScores.reduce((sum, score) => sum + (Number(score) || 0), 0);
  const classification = getClassification(totalScore);

  useEffect(() => {
    form.setValue('classification', classification);
  }, [classification, form]);


  function onSubmit(data: AssetFormValues) {
    onSave({
        ...data,
        id: asset?.id || '', // ID will be generated by parent if new
        assetCode: asset?.assetCode || '', // Asset code will be generated by parent if new
        classification: getClassification(totalScore)
    });
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <FormField
            control={form.control}
            name="name"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Nama Aset</FormLabel>
                <FormControl>
                  <Input placeholder="cth. Server Database Utama" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={form.control}
            name="category"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Kategori</FormLabel>
                <Select onValueChange={field.onChange} defaultValue={field.value}>
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Pilih kategori aset" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    {assetCategories.map(cat => <SelectItem key={cat} value={cat}>{cat}</SelectItem>)}
                  </SelectContent>
                </Select>
                <FormMessage />
              </FormItem>
            )}
          />
        </div>

        <FormField
          control={form.control}
          name="specifications"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Spesifikasi</FormLabel>
              <FormControl>
                <Textarea placeholder="cth. Dell PowerEdge R740, 256GB RAM..." {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <FormField
                control={form.control}
                name="location"
                render={({ field }) => (
                <FormItem>
                    <FormLabel>Lokasi</FormLabel>
                    <FormControl>
                    <Input placeholder="cth. Ruang Server Lt. 1" {...field} />
                    </FormControl>
                    <FormMessage />
                </FormItem>
                )}
            />
            <FormField
                control={form.control}
                name="owner"
                render={({ field }) => (
                <FormItem>
                    <FormLabel>Pemilik</FormLabel>
                    <FormControl>
                    <Input placeholder="cth. Divisi TI" {...field} />
                    </FormControl>
                    <FormMessage />
                </FormItem>
                )}
            />
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <FormField
                control={form.control}
                name="status"
                render={({ field }) => (
                <FormItem>
                    <FormLabel>Status</FormLabel>
                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                        <SelectTrigger>
                        <SelectValue placeholder="Pilih status aset" />
                        </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                        {assetStatuses.map(stat => <SelectItem key={stat} value={stat}>{stat}</SelectItem>)}
                    </SelectContent>
                    </Select>
                    <FormMessage />
                </FormItem>
                )}
            />
             <FormField
                control={form.control}
                name="purchaseDate"
                render={({ field }) => (
                <FormItem>
                    <FormLabel>Tanggal Pembelian</FormLabel>
                    <FormControl>
                    <Input type="date" {...field} />
                    </FormControl>
                    <FormMessage />
                </FormItem>
                )}
            />
        </div>
        <FormField
                control={form.control}
                name="expiryDate"
                render={({ field }) => (
                <FormItem>
                    <FormLabel>Tanggal Kadaluarsa</FormLabel>
                    <FormControl>
                    <Input type="date" {...field} />
                    </FormControl>
                    <FormMessage />
                </FormItem>
                )}
            />

        <Separator className="my-6" />

        <div>
            <h3 className="text-lg font-medium mb-4 font-headline">Penilaian Awal</h3>
            <div className="space-y-4">
                {criteria.map((criterion) => (
                    <FormField
                        key={criterion.id}
                        control={form.control}
                        name={criterion.id as keyof AssetFormValues}
                        render={({ field }) => (
                            <FormItem className="grid grid-cols-3 items-center gap-4">
                                <FormLabel className="col-span-2">{criterion.label}</FormLabel>
                                <Select onValueChange={field.onChange} defaultValue={String(field.value)}>
                                    <FormControl>
                                        <SelectTrigger>
                                            <SelectValue placeholder="Pilih nilai" />
                                        </SelectTrigger>
                                    </FormControl>
                                    <SelectContent>
                                        {scoreOptions.map((option) => (
                                            <SelectItem key={option.value} value={String(option.value)}>
                                                {option.label}
                                            </SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                                <FormMessage className="col-span-3" />
                            </FormItem>
                        )}
                    />
                ))}
            </div>
        </div>

        <Card className="bg-secondary/50 mt-6">
            <CardHeader>
                <CardTitle className="text-lg font-headline">Hasil Penilaian Awal</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-center">
                <div>
                    <p className="text-sm text-muted-foreground">Total Skor</p>
                    <p className="text-4xl font-bold">{totalScore}</p>
                </div>
                <div>
                    <p className="text-sm text-muted-foreground">Klasifikasi Aset</p>
                    <p className="text-2xl font-bold font-headline text-primary">{classification}</p>
                </div>
            </CardContent>
        </Card>


        <div className="flex justify-end gap-2 pt-6">
            <Button type="button" variant="outline" onClick={onCancel}>
                Batal
            </Button>
            <Button type="submit">Simpan</Button>
        </div>
      </form>
    </Form>
  );
}
